### ISSUE TITLE
Update Name View

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/invoke#17]
- [x] Add field for DAO Name
  - Label: DAO
  - Placeholder: Name
- [x] Add Next button (primary)
- [x]  Add validation to DAO name length 

[Figma](https://www.figma.com/file/zJ5U7lEWu0cMCoGaevNv1l/Bootleggers?type=design&node-id=5466-23735)
Frame: Iteration 1 > Name Your DAO

**Comment by earth2travis** [comment]
![Image](https://github.com/0xBootleggers/invoke/assets/522182/fca1080a-91aa-4dcd-8ab0-e95291a24595)

**Comment by skuhlmann** [comment]
- [ ] Add length validation - see current summoner app.
