### ISSUE TITLE
Update Tokens View

### ISSUE THREAD

**Issue by earth2travis** [0xBootleggers/invoke#18]
- [x] Create `<fieldset>` for Voting Token
  - Placeholders: Name, SYMBOL
- [x] Create `<fieldset>` for Non-Voting Token
  - Placeholders: Name, SYMBOL
- [x] Add Previous secondary button
- [x] Add Next primary button

[Figma](https://www.figma.com/file/zJ5U7lEWu0cMCoGaevNv1l/Bootleggers?type=design&node-id=5466-23735)
Frame: Iteration 1 > Configure Token Settings

**Comment by earth2travis** [comment]
![Image](https://github.com/0xBootleggers/invoke/assets/522182/ef091318-3556-4f28-91ba-c135284ef47e)

**Comment by skuhlmann** [comment]
- [ ] Update length validation on fields - see current summoner app validation
